### ISSUE TITLE
Rendering Jupyter Notebooks instead of showing raw code.

### ISSUE THREAD

**Issue by DiGyt** [yusanshi/embed_like_gist#14]
I recently stumbled over this project when looking for ways to embed my notebooks directly from Github, instead of having to additionally save them as gists. Your project looks like the perfect solution for this (so thank you for that).

However, for my application, there is still one decisive problem: I usually want to embed Jupyter Notebooks on my webpage. On GitHub and GitHub gists, Jupyter Notebooks are nicely rendered into HTML, which is perfect for my applications. However, when I use emgithub.com, Jupyter notebooks will be displayed as their raw source code.

I'm not sure if this will blow the scope of your project, but I was really wondering if there are ways for me to get the rendered code instead, or whether you plan to integrate a "Jupyter Notebook" option which would render Jupyter Notebooks in the same way gists do...

Thank you very much for this great tool! 🙏

**Comment by yusanshi** [comment]
A good idea and I don't think it will be out of the scope of the project, since it is called `embed-like-gist`. If GitHub Gist can do this, why not this project.

Besides Jupyter Notebook, I believe the rendering for Markdown files is also needed. Looks like this could be done with some libraries converting `md` or `ipynb` to `html`. Then directly assign the html content to innerHTML...

I agree with you that an option for rendering is needed because if the rendering is automatically done without any option, it would puzzle those who just want to show the source code of Markdown files, and the backward compatibility will be broken.

I think we can add a drop-down `select` tag called "Rendering mode", defaulting to "Raw", and other options are "Markdown", "Jupyter Notebook". The <https://emgithub.com/> page will select a corresponding mode based on file extensions, though can be changed manually. The rendering mode parameter will be added to "Code to embed", and if missing, default to "Raw" to keep the backward compatibility.

I will add this to the plan. But currently I'm busy with my school work :cry:  Anyway, I'll add a `helped wanted` label so maybe someone could do this before I got some free time :)

**Comment by DiGyt** [comment]
Great idea, that sounds perfect!

Please don't feel hurried on anything, I'm still very thankful that this project even exists :)
I must say I'm not much of an expert when it comes to working with HTML and JS, but I can see what I can do there, or if I can find someone to help out here...

**Comment by yusanshi** [comment]
emgithub-v2 is finished with Markdown and Jupyter supporting. Please try and give feedback if any. :smiley: 

Example: <https://emgithub.com/odewahn/ipynb-examples/blob/master/Animations%20Using%20clear_output.ipynb>

![image](https://user-images.githubusercontent.com/36265606/185800077-b95f8ae3-7eb5-4149-b809-d73ed2ef613e.png)

**Comment by DiGyt** [comment]
Hey there,

Wow, this looks absolutely perfect! I already tested it and it works like a charm for all tested notebooks. Awesome work! 🙂
Thank you so much for implementing this. This will definitely make my life a lot easier...🙏

As everything is working nicely, I would close this issue now.
Thank you once more for your great work. I think this will come really handy to a lot of people.
