### ISSUE TITLE
how do i get rid of the 2 empty lines below the last code line when embedding?

### ISSUE THREAD

**Issue by horstjens** [yusanshi/embed_like_gist#2]
i embed python code into a html website using https://emgithub.com/pytorch/pytorch/blob/master/torch/nn/cpp.py

I noticed that below the last code line but above the lower border 
![Screenshot at 2020-04-20 07-44-49](https://user-images.githubusercontent.com/137853/79718144-a1aade80-82db-11ea-9b20-09074067c913.png)
of the code container seem to be 2 empty lines, how can i disable them?

**Comment by yusanshi** [comment]
I think this's because the environment where the code is shown is adding other CSS styles for the `pre` tag. To solve this, I decide to use a simulated `pre` tag to avoid style being added or overwritten. (See 18ba04cb8ffe7500893e0d25d63f59e8e4b052f1)

In this way, what you see on the page where code is embedded should look basically the same as it is on emgithub.com.
