### ISSUE TITLE
wrong colors in python multi-line code blocks / python \n escape character

### ISSUE THREAD

**Issue by horstjens** [yusanshi/embed_like_gist#3]
I noticed that code coloring  makes strange results especially when processing multi-line python code (python code line that goes over several physical lines).
example:
trying to embed this code:
https://github.com/horstjens/ThePythonGameBook/blob/master/python/tictactoe/002b_crude_display.py
![Screenshot at 2020-04-20 07-55-04](https://user-images.githubusercontent.com/137853/79718695-eaaf6280-82dc-11ea-969f-aa42048a2013.png)

Possibly same problem: a one-line python code looses it correct coloring. Maybe because it included a "\n" ? 
![Screenshot at 2020-04-20 08-01-42](https://user-images.githubusercontent.com/137853/79719071-f8b1b300-82dd-11ea-849d-3e74d601775a.png)
![Screenshot at 2020-04-20 08-01-59](https://user-images.githubusercontent.com/137853/79719072-f94a4980-82dd-11ea-87e2-41a201035b59.png)

**Comment by yusanshi** [comment]
The problem is about language detection of highlightjs, which I used as highlighting engine.

highlight.js can detect language based on code content but that can be inaccurate sometimes. Now I have specified the language by passing the file extension to hightlight.js.

![image](https://user-images.githubusercontent.com/36265606/79862247-66f29480-8408-11ea-95ee-2c3f134c1028.png)
![image](https://user-images.githubusercontent.com/36265606/79862357-8f7a8e80-8408-11ea-8038-15b6792f8ce2.png)
