### ISSUE TITLE
How long is the file cached?

### ISSUE THREAD

**Issue by ppwfx** [yusanshi/embed_like_gist#4]
Hey,

I just updated the contents of a file, but the content of the embedded code didn’t change. Is there are workaround for that?

Really nice tool btw! Appreciate it :)

**Comment by yusanshi** [comment]
Well, do a force-refresh by `Ctrl + F5`, may help.

Say if you have embedded the file <https://github.com/yusanshi/embed-like-gist/blob/master/404.html> into a webpage. While loading, your browser is instructed to try to fetch the file <https://raw.githubusercontent.com/yusanshi/embed-like-gist/master/404.html>.  After being fetched, the file is cached. When you refresh the page, your browser may load the cached file instead of the new one.

Although it is possible to force your browser to not use cached one by adding a parameter to [`fetch`](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API/Using_Fetch), I don't think it is necessary. Just leaving it as default is not bad. It seems that the cache option from response is `max-age=300`, i.e., the cache will live for no more than 5 minutes.
![image](https://user-images.githubusercontent.com/36265606/82118609-fc383d00-97aa-11ea-8f1d-f92082295ec3.png)

Thx for your appreciation!

**Comment by ppwfx** [comment]
Hey @yusanshi,

I just had another look into it and github itself cached the raw version of the file for a bit.

Again, thanks a lot for this tool! It's so good, actually deserves at least 10 times as many stars!
