### ISSUE TITLE
Embed only certain lines

### ISSUE THREAD

**Issue by myroslambda** [yusanshi/embed_like_gist#5]
I have implemented a solution to embed only certain lines. It introduces two new arguments. See https://github.com/myroslambda/embed-like-gist/commit/890c829e26e396b207bd3c0e3bb2324d0cd263f7

The only thing that does not work is line numbering. I know where to put it, but the PR in highlighjs-line-numbers has not been accepted yet: https://github.com/wcoder/highlightjs-line-numbers.js/pull/65

Would it make sense to add this to the project, and maybe to ping  https://github.com/wcoder/ and ask if that PR can be accepted?

**Comment by myroslambda** [comment]
I got a message that that PR was accepted in highlightjs-line-numbers, so this one would only require one small change. If you think it can be accepted I can make the change in my fork and send a PR.

@yusanshi ?

**Comment by yusanshi** [comment]
Good job! Thanks a lot. 😃
Since it was integrated into 2.8.0, using this will be fine.
`https://cdn.jsdelivr.net/npm/highlightjs-line-numbers.js@2.8.0/dist/highlightjs-line-numbers.min.js`

Also, maybe we should add two input boxes in `404.html`.

Btw, sorry for my late reply. I noticed this issue, but I'm quite busy you know😅

**Comment by myroslambda** [comment]
OK. I will prepare and send a PR. Thank you!

**Comment by yusanshi** [comment]
Hey guy, #6 is merged so I'll close this issue.

Anyway, thank you!😁

**Comment by myroslambda** [comment]
That's ok. I have been really busy and did not have time to send the PR. Thank you!
