### ISSUE TITLE
I found that there some code styles are different from GitHub and Gist.

### ISSUE THREAD

**Issue by fantasticmao** [yusanshi/embed_like_gist#7]
Hi, it's me again.

As mentioned in the title, **FIRST**, I found that GitHub uses 4 spaces as TAB indentation width, but `highlight.js` use 8 spaces as default. See the following two pictures for details.

The display style in GitHub:

![image](https://user-images.githubusercontent.com/20675747/88014791-56aa9c80-cb52-11ea-9214-bde97cfb9a8b.png)

The display style in EmGitHub:

![image](https://user-images.githubusercontent.com/20675747/88014660-0fbca700-cb52-11ea-8309-ed2de69fd0af.png)

I wonder if we can make them consistently, in order to avoid wasting space.

**SECONDLY**, I found that Gist's CSS style uses a font size of 12px `gist-meta: { font: 12px ... }`, and EmGitHub uses a font size of 0.8rem `file-meta:{ font: 0.8rem ... }`. 

https://github.com/yusanshi/embed-like-gist/blob/08eaecb705659cc9253a9688461987b20cdad8f7/embed.js#L32-L37

In my user experience, on a page that contains both Gist and EmGitHub, it looks a little strange that the font size is different, but it’s okay.

**FINALLY**, I wonder if we can use the `params.toString()` value as the `id` attribute of the outermost div and change the `class` attribute to a common class name. Because I hope I can modify some styles of EmGitHub externally by matching the class name, or is there any other way to implement this 🤔

https://github.com/yusanshi/embed-like-gist/blob/08eaecb705659cc9253a9688461987b20cdad8f7/embed.js#L5

https://github.com/yusanshi/embed-like-gist/blob/08eaecb705659cc9253a9688461987b20cdad8f7/embed.js#L28

**Comment by fantasticmao** [comment]
The way to change the TAB width in `highlight.js` is in this issue: https://github.com/highlightjs/highlight.js/issues/508

**Comment by yusanshi** [comment]
Thanks for your suggestions!

*All the changes are made at branch [improve-code-display](https://github.com/yusanshi/embed-like-gist/tree/improve-code-display). You can try and test yourself. If that is OK to you, we can merge it into master :)*

# TAB width

Sorry but after searching it seems that 8 is the default width for TAB.
- https://stackoverflow.com/questions/50524579/how-to-set-tab-size-in-github-web-interface
- https://github.com/isaacs/github/issues/170
- https://stackoverflow.com/questions/8833953/how-to-change-tab-size-on-github

Also I did a test, TABs in the files were rendered as 8 space width, on my PC and phone.
- https://github.com/yusanshi/embed-like-gist/blob/test/test-tab-width.java
- https://github.com/yusanshi/embed-like-gist/blob/test/test-tab-width.txt

![image](https://user-images.githubusercontent.com/36265606/88453688-e2e2f980-ce9b-11ea-9128-45285f617460.png)

So I think directly setting TAB size to 4 is not ideal. 

However, on GitHub web surface, TAB width can be specified by `?ts=X`, I think we can take it into this project. Although `hljs.configure({tabReplace: '    '})` does work, I didn't use this since it will modify the original content, i.e. you copy the code but all TABs become spaces. I use CSS style `tab-size: X` instead. In fact, I found that GitHub implements `ts=X` using `tab-size: X`.

Currently, <https://github.com/yusanshi/embed-like-gist/blob/test/test-tab-width.java?ts=2#L2-L4> in this project should behave basically the same as it does on GitHub web interface.

# Font size

Make sense! Changed to `12px`.

# Id and class

Good suggestion! Currently id is used to locate DIV (to support the same code embedded many times, a random string instead of `params.toString()` is used). 
Also, The outermost div has a class attribute `emgithub-container`. So you can do any hacks you want.

**Comment by fantasticmao** [comment]
Well, it may be that `.editorconfig` affects the TAB size on GitHub 😅

I have tested them all and everything is working fine! Thank you very much!

**Comment by yusanshi** [comment]
I'll close this issue and merge the PR
